Added houdini-leaf worklet
GoogleChromeLabs/houdini.how pull request #129
Opened 2020-12-13 03:18 UTC by zhenyanghua

@una Thanks for sharing this great resource. I just watched your talk on Chrome Dev Summit, and cannot believe there is such awesome tool here. Here is my first worklet.

2020-12-13 03:54 UTC, una requested changes
Thank you for this PR! I love the effect, just left a few comments ☺️ cheers!

2020-12-13 03:54 UTC, una commented on worklets/houdini-leaf.json
> +      "range": [8, 32]
I made the range a bit wider and liked the effect — how about [5, 50]?

2020-12-13 03:54 UTC, una commented on worklets/houdini-leaf.json
> +      "default": "black"
I think it would be nice to have a green shade here. What do you think of `#73ce8f`

2020-12-13 03:54 UTC, una commented on worklets/houdini-leaf.json
> +  "html": "<div style='width: 100%; height: 100px; background-color: wheat; display: flex; justify-content: center; align-items: center;'>Leaf and Vine</div>",
I think you can get rid of this `html` bit entirely. It looks good on its own as a background:

<img width="894" alt="Screen Shot 2020-12-12 at 10 51 44 PM" src="https://user-images.githubusercontent.com/1693164/102002685-e6e9a980-3ccc-11eb-90b8-129ab7cf2361.png">

2020-12-13 12:01 UTC, nucliweb commented
Thank you @zhenyanghua for the contribution, is a beautiful Paint Worklet.

**Can you optimize the avatar image?**

## e.g.
![zhenyang](https://user-images.githubusercontent.com/1307927/102010991-d7587800-3d41-11eb-8d99-876baf0bba08.jpg)

| Original | Optimized |
| -- | -- |
| <img width="283" alt="Screen Shot 2020-12-13 at 12 55 32" src="https://user-images.githubusercontent.com/1307927/102011199-1509d080-3d43-11eb-917a-05e8becfd89a.png"> | <img width="290" alt="Screen Shot 2020-12-13 at 12 56 12" src="https://user-images.githubusercontent.com/1307927/102011212-2357ec80-3d43-11eb-85d6-101378d4dcd2.png"> |

2020-12-13 16:13 UTC, zhenyanghua commented on worklets/houdini-leaf.json
> +      "range": [8, 32]
Good idea, widened it.

2020-12-13 16:15 UTC, zhenyanghua commented on worklets/houdini-leaf.json
> +      "default": "black"
I like the color you suggested better.

2020-12-13 16:15 UTC, zhenyanghua commented on worklets/houdini-leaf.json
> +  "html": "<div style='width: 100%; height: 100px; background-color: wheat; display: flex; justify-content: center; align-items: center;'>Leaf and Vine</div>",
I love this suggestion, it is perfect. Thanks!!

2020-12-13 16:17 UTC, zhenyanghua commented
@nucliweb Great tip! Thanks. I compressed it into [`webp`](https://developers.google.com/speed/webp/docs/using) format. That is also something I just learned from the past chrome dev summit.

2020-12-13 22:57 UTC, nucliweb approved these changes

2020-12-14 16:33 UTC, una commented
Thanks @zhenyanghua! If you can just removed the `package-lock.json` I'll merge this in :)

2020-12-14 19:00 UTC, zhenyanghua commented
@una, good catch. all set, that got slipped in.

2020-12-14 19:01 UTC, una approved these changes

2020-12-14 19:01 UTC, merged