Add Fractals Demo
GoogleChromeLabs/houdini.how pull request #135
Opened 2020-12-15 10:25 UTC by ConradSollitt

Here is the working demo (repository link is on the page):
https://conradsollitt.github.io/css-houdini-fractals/

Since fractals use recursive functions I have a safety check in place and use reasonable defaults to avoid long delays. One the demo there is a variable that allows for CSS output to the console so you can see how many functions were called and how fast it runs on your machine.

Tested browsers:
* Chrome (Latest)
* Firefox on Mac
* Safari on Mac Desktop _For Safari Desktop, I find I have to change an initial value for rendering to show; it doesn't render on page load._
* Safari on iOS

For my demo I need to improve the layout for mobile browsers (likely tomorrow or later this week).

Also the current defaults may need to be adjusted for smaller size or based on need for better performance on initial page load. Here is a quick test of `240x240px` using defaults that result in much less rendering and render in milliseconds. The defaults I specified can take about 20 milliseconds which may or may not be acceptable for the initial page load.

![image](https://user-images.githubusercontent.com/57777521/102202059-be53e200-3e7b-11eb-822d-e30b77a53537.png)

Tomorrow (actually later today - it's 2:20 AM where I live in Los Angeles 🤦‍♂️) I'm happy to help make any additional changes needed or help with more test. Or whatever time works!

Awesome site by the way!!! I have read about CSS Houdini before but wasn't sure if it was something I would ever use but after seeing https://houdini.how/ I think there is a lot of great use and options for it.

2020-12-15 10:28 UTC, ConradSollitt commented
@googlebot I signed it!

2020-12-15 11:33 UTC, ConradSollitt commented
After playing around with the demo some more I think changing the `--max-draw-count` from `100,000` to `10,000` (commas here for clarity) would be a good idea. It keeps the rendering much more performant when using the range controls and if the user generates large fractals it provides an interesting effect by default as half the screen can be drawn and rotate as the user drags the angle.

2020-12-15 22:12 UTC, nucliweb approved these changes
Great Worklet, thanks @ConradSollitt 👏🏼

2020-12-15 23:35 UTC, ConradSollitt commented
Thanks @nucliweb

2020-12-16 09:29 UTC, ConradSollitt commented
Two minor issues I found when testing the site locally:
* I specified strings that are too long to fit nicely (screen below)
* The variable `--max-draw-count` uses very large numbers (currently defaults to 100_000) so it doesn't fit on screen.
![image](https://user-images.githubusercontent.com/57777521/102328965-a001eb00-3f3c-11eb-8587-08dde5083e77.png)

I'm not sure if I can update the pull request for it or if I should wait till after this one is merged (to avoid issues I feel like I should wait). Basically I'll remove some 1 color on the default list a a few from the gray scale list and then `--colors` can fit to visually like up with all other items.

As I mentioned before I'll revise down the default available value for `--max-draw-count` and I also think it makes since to limit the range to 50_000 and use step of 1000 but I can make that later as well.

Noice on the screenshot below the input for `--max-draw-count` is wider than other numeric inputs.

![image](https://user-images.githubusercontent.com/57777521/102328981-a42e0880-3f3c-11eb-8f96-39df68b28d8f.png)

I was able to do that through CSS alone, however it requires a known attribute value. Would this update (highlighted code below) be acceptable if I were to submit a pull request for it?

Although it would be specific to my worklet it could be easily tweaked for future worklets if any use large numbers. I am not aware of any CSS that would let me calculate the number of characters to determine what the input length should be and making the change in CSS avoids adding extra props to JSON and JSX code.

![image](https://user-images.githubusercontent.com/57777521/102328998-aa23e980-3f3c-11eb-8131-4d24eb6007d1.png)

2020-12-16 20:16 UTC, una commented
Thanks, I'll take a look at the CSS to avoid hiding this number. VERY cool worklet!

2020-12-16 21:32 UTC, una requested changes
Thanks for this PR! Just left a few questions :)

2020-12-16 21:32 UTC, una commented on worklets/fractals.json
> +      "step": "0.1"
I would make this still smaller (try `0.05`)

2020-12-16 21:32 UTC, una commented on worklets/fractals.json
> +      "range": [0, 2000000],
This feels like a massive range for this demo, and as you mentioned, there are viewport issues. Would you be open to decreasing the range here?

2020-12-16 21:32 UTC, una commented on worklets/fractals.json
> +      "range": [0, 1],
Should this be true/false instead of `[0,1]`? Is it necessary for the demo? I might remove it since it seems like a debugging option rather than related to the painting

2020-12-16 21:32 UTC, una commented on worklets/fractals.json
> +      "options": [
You could leave this as a blank string so that users can enter their own colors. Up to you, but most of the worklets which accept multiple colors as a string like this are open-ended.

2020-12-16 23:10 UTC, ConradSollitt commented on worklets/fractals.json
> +      "step": "0.1"
Good idea! Should I make the edits in this pull request?

Looks like I can use the online editor to do this (can't remember the last time I updated an existing pull request though so I just wanted to make sure).

2020-12-16 23:16 UTC, ConradSollitt commented on worklets/fractals.json
> +      "range": [0, 2000000],
Yes, after seeing your comment on `--debug-to-console` I feel like this can simply be removed as well.

Currently the demo points to: `https://unpkg.com/css-houdini-fractals@1.0.0/fractals.js`

If removing it I think I should publish a new `1.0.1` version with a lower default `10,000` instead of `100,000`. As I mentioned before the main purpose of it is too prevent long running paints.

2020-12-16 23:18 UTC, ConradSollitt commented on worklets/fractals.json
> +      "range": [0, 1],
I think we can just remove it. It's related to debugging (but not real debugging) - more of interest on how many function calls are made to render the drawing.

2020-12-16 23:18 UTC, ConradSollitt commented on worklets/fractals.json
> +      "options": [
Yeah I agree, let's leave it open ended.

2020-12-16 23:23 UTC, ConradSollitt commented on worklets/fractals.json
> +      "range": [0, 2000000],
Related to a different CDN version if I were to make that change I could add one new option for `--shape` which I have been testing locally:

**Example: circle**

![image](https://user-images.githubusercontent.com/57777521/102418434-91eeb180-3fb2-11eb-8738-ff37457bfbdd.png)

2020-12-17 02:00 UTC, ConradSollitt commented
@una I just made the updates on this pull request and when I click the `Files changed` tab the `fractals.json` file look good.

The update points to the `1.1.0` release rather than `1.0.0` and it includes the new `--shapes` property I wrote about in my earlier comment. Rather than pointing the CDN link to always use the latest I point it a specific version just in case I decide to make updates one day then nothing would break on https://houdini.how/ because it will point to the correct version for the variables.

![image](https://user-images.githubusercontent.com/57777521/102432130-1d267200-3fc8-11eb-85bb-00fbf2c3be4f.png)

2020-12-22 07:00 UTC, ConradSollitt commented
@una Unrelated to this but I just realized right now when I was updated my personal site earlier this year (link below) one of the things that helped me come up with a nice Text Effect for the `<h1>` header was one of your articles (link also below). I listed 7 helpful links in the CSS comments and put your's first. So great job on your site because I found the content to be of top quality and found I could to learn from and get ideas from as well. 😄 

**My personal site - one page**
https://conradsollitt.com/
_When I submitted on awwwards I got 4 perfect 10's, many high 9's and my highest score overall compared to past sites. I think in part because of the text effect. Also got a 5 and 6 score so can't win everyone._

**Your great Dynamic Color Article**
https://una.im/css-color-theming/

2021-01-08 16:40 UTC, merged

2021-01-08 16:40 UTC, una commented
Thank you Conrad!