(Worklet) Add bubbles demo
GoogleChromeLabs/houdini.how pull request #149
Opened 2021-01-22 15:39 UTC by AKAspanion

This PR adds css-houdini-bubbles as a demo

<img width="935" alt="Screenshot 2021-01-22 at 8 59 33 PM" src="https://user-images.githubusercontent.com/25038931/105511165-9f0b6880-5cf5-11eb-9673-1b91a4f775cb.png">
Demo: https://codepen.io/spanion/pen/rNMgerx

2021-01-22 21:34 UTC, nucliweb approved these changes
😊Very nice,  I love it!

2021-01-30 22:36 UTC, una requested changes
LOVE this effect! Just left a few very small comments for the demo 😄

2021-01-30 22:36 UTC, una commented on worklets/bubbles.json
> +        "default": "#007C8E, #7940c1"
I'd recommend using readable colors for the demo, i.e. `deepskyblue, pink`

2021-01-30 22:36 UTC, una commented on worklets/bubbles.json
> +        "default": "20",
I like `10` or `12` as the default in this space -- it feels less crowded

2021-01-31 11:06 UTC, AKAspanion commented on worklets/bubbles.json
> +        "default": "#007C8E, #7940c1"
Changed colors to `teal, blueviolet`.

2021-01-31 11:06 UTC, AKAspanion commented on worklets/bubbles.json
> +        "default": "20",
Changed default value to `12`.

2021-01-31 11:07 UTC, AKAspanion commented
Thanks for the suggestion @una. I have updated the same. 😀

2021-02-01 20:50 UTC, merged

2021-02-01 20:50 UTC, una commented
🎉🎉🎉