Add the houdini-alien worklet
GoogleChromeLabs/houdini.how pull request #159
Opened 2021-04-06 16:06 UTC by andreban

A Worklet that uses the CSS Paint API to render a background
that looks alien.

2021-04-06 18:42 UTC, una requested changes

2021-04-06 18:42 UTC, una commented on worklets/alien.json
> +      "default": "1px"
```suggestion
      "default": "2"
```

I think this works without the px. Also `2` has a little less visual vibration

2021-04-06 19:08 UTC, andreban commented on worklets/alien.json
> +      "default": "1px"
Sounds good to me. Applied.

2021-04-07 15:03 UTC, una approved these changes

2021-04-07 15:03 UTC, merged